### ISSUE TITLE
Add a continuous integration/delivery procedure

### ISSUE THREAD

**Issue by liberostelios** [tudelft3d/website#15]
I believe that we could use the current script under "update" to run a simple CI build every time someone pushes a new commit and get an early notification when something breaks the website.

In the future, that might also mean we could use pull requests to update the code here and, as soon as the PR is merged successfully, a continuous delivery process could trigger http://3d.bk.tudelft.nl/update.

**Comment by balazsdukai** [comment]
I think Travis is already set up for one of the repos, don't remember which. We can use that.

**Comment by Ylannl** [comment]
perhaps the new GitHub Actions are useful for this? 
https://github.com/tudelft3d/website/actions

**Comment by Ylannl** [comment]
I set up a github actions workflow that does a jekyll build on each push. It is rather slow because ‘gem install jekyll’ pulls in a bazillion dependencies.

**Comment by balazsdukai** [comment]
Pulling in the docker image [https://github.com/tudelft3d/website/blob/master/Dockerfile](https://github.com/tudelft3d/website/blob/master/Dockerfile), instead of installing the deps each time, might make things faster. 
I have a tudelft3d user set up on Docker Hub, let me know if you want the image there.

**Comment by Ylannl** [comment]
> Pulling in the docker image https://github.com/tudelft3d/website/blob/master/Dockerfile, instead of installing the deps each time, might make things faster.
Good idea. But if I understand correctly there is already an image with just jekyll. That should be good enough with your docker file. I'll look into that.

Next step should be to trigger the update script on our server. It is not so easy to do this with `curl` because of the https. Maybe we can connect through ssh.

**Comment by Ylannl** [comment]
Turns out triggering the update script was very easy after all using `curl` with the `-L` option. Automatic update is working now. No more need to manually visit the /update page!
